# ===== GIAI ĐOẠN 1: BUILD =====
FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn package -DskipTests

# ===== GIAI ĐOẠN 2: RUN =====
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

# Chỉ lấy file .jar từ builder (GĐ1)
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

# Lệnh chạy ứng dụng Spring Boot
ENTRYPOINT ["java", "-jar", "app.jar"]
